apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt2openmetrics.fullname" . }}-config
  labels:
    {{- include "mqtt2openmetrics.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- .Values.config | required "config is required" | toYaml | nindent 4 }}
